- lib/index.ts
Closes issue - https://github.com/tscircuit/tscircuit/issues/215
> props added for oval

- .gitignore
- biome.json
- lib/index.ts
- package-lock.json
- package.json
- **add support for cadModel prop**
- **add biome, extend cadModel with positionOffset and rotationOffset**
> add biome, extend cadModel with positionOffset and rotationOffset

- .github/workflows/formatcheck.yml
- .github/workflows/npm-typecheck.yml
- lib/index.ts
- package.json
- tsconfig.json
- **add formatter and format check**
- **add typecheck workflow**
> Typecheck & Format Workflows

- lib/index.ts
- package-lock.json
- package.json
Closes - https://github.com/tscircuit/tscircuit/issues/262
> feat: Add manufacturer part number

- lib/index.ts
- package-lock.json
- package.json
Closes - https://github.com/tscircuit/tscircuit/issues/264
> feat: trace width added

- lib/index.ts
- package.json
> feat: add SwitchProps

- lib/index.ts
to support new syntax
```tsx
<trace>
<tracehint offset={{ x: 0, y: "1mm" }} />
</trace>
```
> make <tracehint for="..." /> optional

- .github/workflows/formatbot.yml
> Update formatbot to not run against forks

- lib/common/layout.ts
> Revert "add schWidth and schHeight, pcbWidth and pcbHeight"

- .gitignore
- docs/CIRCUIT_JSON_PCB_OVERVIEW.md
- lib/components/platedhole.ts
- lib/index.ts
CC @andrii-balitskyi i think this may be necessary for some easyeda conversions
- **refactor platedhole into it's own file**
- **add pill support**
> Add <platedhole shape="pill" /> support

- lib/common/layout.ts
- lib/components/board.ts
- lib/components/group.ts
- lib/components/netalias.ts
- lib/typecheck.ts
- **fix net alias, add support for partsEngine prop**
- **improve type checks, add partsEngine, refactor board for better subcircuit compat**
> Introduce partsEngine prop, minor refactoring, fix netalias schX definition

- lib/components/pin-header.ts
Issue - https://github.com/tscircuit/core/issues/278
> feat: pin header direction

- lib/components/trace.ts
The core implementation is ready I just need to merge this.
> added trace prop schDisplayLabel

- lib/index.ts
- lib/manual-edits/index.ts
- lib/manual-edits/manual-edit-events/base_manual_edit_event.ts
- lib/manual-edits/manual-edit-events/edit_component_location_event.ts
- lib/manual-edits/manual-edit-events/edit_trace_hint_event.ts
- lib/manual-edits/manual-edit-events/index.ts
- lib/manual-edits/manual_edit_event.ts
- lib/manual-edits/manual_edit_file.ts
- lib/manual-edits/manual_pcb_position.ts
- lib/manual-edits/manual_trace_hint.ts
- **manual edits**
- **bootstrap manual edit definitions**
> Move Manual Edits Definitions into Props

- lib/components/resonator.ts
- tests/resonator.test.ts
> fix: resonator pin variant property

- lib/components/transistor.ts
- lib/index.ts
- tests/transistor.test.ts
- add transistorProps
Fixes #126
> add transistorProps

- lib/components/chip.ts
- tests/chip1-basic.test.ts
- tests/chip2-schematic-port-arrangement.test.ts
- added noSchematicRepresentation property to chipProps
Fixes #140
> add noSchematicRepresentation prop to chip

- lib/common/layout.ts
- lib/components/diode.ts
- lib/components/fabrication-note-path.ts
- lib/components/fabrication-note-text.ts
- lib/components/inductor.ts
- lib/components/led.ts
- lib/components/pcb-keepout.ts
- lib/components/pcb-trace.ts
- lib/components/port.ts
- lib/components/power-source.ts
- lib/components/schematic-box.ts
- lib/components/schematic-line.ts
- lib/components/schematic-path.ts
- lib/components/schematic-text.ts
- lib/components/silkscreen-circle.ts
- lib/components/silkscreen-line.ts
- lib/components/silkscreen-path.ts
- lib/components/silkscreen-rect.ts
- lib/components/silkscreen-text.ts
- lib/components/switch.ts
- lib/components/trace-hint.ts
- lib/components/via.ts
- lib/index.ts
I found a way to parse these types into a simple file for the AI, I just need to cleanup a little
> cleanup folder structure

- generated/COMPONENT_TYPES.md
- package.json
- scripts/generate-component-types.ts
@seveibar does this look good for the AI? please review the md
> script to generate component types

- lib/common/schematicPinDefinitions.ts
- lib/components/chip.ts
- lib/components/push-button.ts
- **add default configuration for internally connected push button pins**
- **rename internallyConnectedPorts to internallyConnectedPins**
- **rename schPortArrangement to schPinArrangement**
> Rename schPortArrangement to schPinArrangement, rename internallyConnectedPorts to internallyConnectedPins

- lib/components/pin-header.ts
> add schFacingDirection prop to pinHeaderProps

- lib/components/switch.ts
relates to #https://github.com/tscircuit/core/issues/585
> improve switch props

- lib/components/crystal.ts
- tests/crystal.test.ts
> change crystal pin from 2pin to two_pin

- lib/components/chip.ts
- tests/chip1-basic.test.ts
> add connections prop to chip

- lib/components/switch.ts
- tests/switch.test.ts
> add switch test

- lib/components/capacitor.ts
> add maxVoltageRating to capacitor

- lib/components/capacitor.ts
> add schShowRatings to capacitor

- lib/components/platedhole.ts
- tests/platedhole.test.ts
fixes #188 
this is from circuit-json
> add support rect plated with circular hole

- generated/COMPONENT_TYPES.md
- scripts/generate-component-types.ts
> add missing component types eg: silkscreen

- lib/components/chip.ts
- tests/chip1-basic.test.ts
- tests/chip2-schematic-port-arrangement.test.ts
> feat: Introduce ChipProps<PinLabel extends string>

- lib/components/chip.ts
- lib/components/push-button.ts
- tests/chip1-basic.test.ts
- tests/chip2-schematic-port-arrangement.test.ts
- tests/chip3-type-tests.test.tsx
- tsconfig.json
- **checkpoint new chip props**
- **More advanced ChipProps**
> More Advanced Types for ChipProps to enable better selectors

- lib/components/diode.ts
- tests/diode.test.ts
related to https://github.com/tscircuit/core/issues/719
> add connections prop to diode

- lib/components/platedhole.ts
- tests/platedhole.test.ts
- **Pill plated hole should use holeWidth/holeHeigth instead of innerWidth/innerHeight**
- **Test**
> Pill plated hole should use holeWidth/holeHeigth instead of innerWidth/innerHeight

- lib/common/connectionsProp.ts
- lib/components/capacitor.ts
- lib/components/resistor.ts
- **add connections prop for resistor**
- **add capacitor connections definition**
> Add `connections` prop for resistor and capacitor

- lib/components/board.ts
related to https://github.com/tscircuit/3d-viewer/issues/139
> added material prop with fr4 as a default and fr1 as an option

- lib/components/schematic-text.ts
related to : https://github.com/tscircuit/core/issues/785
> added anchor and color to schematicTextProps for the <schematictext />

- .github/workflows/update-readme.yml
- .gitignore
- README.md
- package.json
- scripts/generate-readme-docs.ts
- **init generate readme docs**
- **add links to props definitions**
> Docs Generation

- lib/components/platedhole.ts
- tests/platedhole.test.ts
> fix: convert shape enum to snake_case in plated hole props

- lib/components/led.ts
REF: https://github.com/tscircuit/core/issues/759
> feat(refractor): add wavelength to led props

- lib/components/transistor.ts
> add igbt transistor type in transistor props

- generated/COMPONENT_TYPES.md
- generated/PROPS_OVERVIEW.md
- lib/common/cadModel.ts
merged without pr
This reverts commit eacaf1285fdde2910f5e50aeaa5dedfc1e09afa7.
second time this week, and it will keep happening if we don't add protection
> Revert "feat(props): add support for glb, step, and wrl cad models"
